language: java
jdk:
  - openjdk7

# This before_script sets up xvfb, which is a fake display that can run Firefox for browser based testing.
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

# See diagram here for default gradle task dependencies
# https://docs.gradle.org/current/userguide/java_plugin.html
# We have added a few dependencies to check.

# Build the code first, before testing
install: gradle assemble

# Run all tests
# `gradle build` should run compile, test, restTest, integrationTest, check, assemble
script: gradle build

# Run buildProduct (via gretty), installProduct, startProduct, testInstalledProduct, stopProduct
script: gradle testInstalledProduct

