language: java
jdk:
  - openjdk7

# This before_script sets up xvfb, which is a fake display that can run Firefox for browser based testing.
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

# `gradle build` should run compile, test, restTest, integrationTest, package
script: gradle build
